version: '2'

services:
   wordpressdb:
     image: mysql:5.7
     volumes:
       - wordpress_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ${BRN_MYSQL_WORDPRESS_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${BRN_MYSQL_ROOT_PASSWORD}

   wordpress:
     depends_on:
       - wordpressdb
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wordpressdb:3306
       WORDPRESS_DB_PASSWORD: ${BRN_MYSQL_WORDPRESS_PASSWORD}
       WORDPRESS_DB_USER: wordpress
       VIRTUAL_HOST: www.benrowland.net
volumes:
    wordpress_db_data:
